###

GET http://localhost:3000/comments

###
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postID": "673b78ba056cb1dd388364b4",
  "content": "New comment",
  "sender": "amit"
}